"""empty message

Revision ID: ce9cdbb7ebb0
Revises: 3e88996d0806
Create Date: 2024-04-04 15:54:08.215989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9cdbb7ebb0'
down_revision: Union[str, None] = '3e88996d0806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False, comment='Email is used as login'),
    sa.Column('password', sa.String(), nullable=False, comment='Hashed password'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False, comment="User's nickname to be used in chat"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
